import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppPorivders from "@/components/providers/app-providers";
import {ClerkProvider} from "@clerk/nextjs"
import { Toaster } from "@/components/ui/sonner";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <ClerkProvider afterSignOutUrl="/sign-in" appearance={{elements: {formButtonPrimary: "!bg-primary hover:!bg-primary/90 !text-sm !shadow-none"}}}>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
          <AppPorivders>
            {children}
          </AppPorivders>
        </body>
        <Toaster richColors/>
      </ClerkProvider>
    </html>
  );
}
