import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { ExecutionLog } from '@/lib/generated/prisma'
import { cn } from '@/lib/utils';
import { LogLevel } from '@/types/log';

type Props = {
    logs?: ExecutionLog[]
}

const LogViewer = (props: Props) => {
    if(!props.logs || props.logs.length === 0) return null;

  return (
    <Card className='py-0'>

        <CardHeader className='rounded-lg rounded-b-none border-b py-4 bg-gray-50 dark:bg-background'>
            <CardTitle className='text-base'>Logs</CardTitle>
            <CardDescription className='text-sm text-muted-foreground'>Logs generated by this phase</CardDescription>
        </CardHeader>

        <CardContent className='p-0'>

            <Table>

                <TableHeader className='text-muted-foreground text-sm'>

                    <TableRow>

                        <TableHead>TIme</TableHead>
                        <TableHead>Level</TableHead>
                        <TableHead>Message</TableHead>

                    </TableRow>

                </TableHeader>

                <TableBody>
                    {props.logs.map((log, index) => (

                        <TableRow key={index} className='text-muted-foreground'>

                            <TableCell width={190} className='text-xs text-muted-foreground p-[2px] pl-4'>{log.timestamp.toISOString()}</TableCell>
                            <TableCell width={80} className={cn("uppercase text-xs font-bold p-[3px] pl-4", 
                                log.logLevel as LogLevel === "error" && "text-destructive",
                                log.logLevel as LogLevel === "info" && "text-green-600"
                                )}>{log.logLevel}</TableCell>
                            <TableCell className='text-sm flex-1 p-[3px] pl-4'>{log.message}</TableCell>
                            

                        </TableRow>

                    ))}
                </TableBody>

            </Table>

        </CardContent>

    </Card>
  )
}

export default LogViewer