import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import React from 'react'

type Props = {
    title: string, 
    subtitle: string, 
    paramJSON: string | null
}

const ParammeterViewer = (props: Props) => {
    const inputs : Record<string, string> | undefined = props.paramJSON ? JSON.parse(props.paramJSON) : undefined;
  return (
    <Card className='py-0'>
        
        <CardHeader className='rounded-lg rounded-b-none border-b py-4 bg-gray-50 dark:bg-background'>
            <CardTitle className='text-base'>{props.title}</CardTitle>
            <CardDescription className='text-sm text-muted-foreground'>{props.subtitle}</CardDescription>
        </CardHeader>

        <CardContent className='py-4'>

            <div className='flex flex-col gap-2'>
                { ( !inputs || Object.keys(inputs).length === 0 ) && (

                    <p className="text-sm">No parameters generated by this phase</p>

                )}


                {inputs && Object.entries(inputs).map( ( [key, val] ) => (
                    <div className="flex justify-between items-center" key={key}>
                        <p className="text-sm text-muted-foreground flex-1 basis-1/3">{key}</p>

                        <Input readOnly className='flex-1 basis-2/3' value={val as string}/>
                    </div>
                ))

                }

            </div>

        </CardContent>

    </Card>
  )
}

export default ParammeterViewer